name: Run Tests on Push and Pull Request
on:
    push:
        branches:
            - main
        paths-ignore:
            - "__tests__/**"
    pull_request:
        branches:
            - main
        paths-ignore:
            - "__tests__/**"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "20"
            - name: Install Dependencies
              run: yarn install
            - name: Run Tests
              run: yarn test